use github contents api for image urls + summer cleaning (#253)
* nix: alejandra -> nixfmt-rfc-style

* nix: pre-commit-hooks -> treefmt-nix

* nix: use corepack

* ci: cleanup workflows

* ci: use better dependabot scopes

* gitignore: extend with github templates

* remove teawie-archive submodule

* pnpm: 8.8.0 -> 9.6.0

* nix: add nrr to shell

* nix: add node lsps to shell

* use github contents api for image urls

* ci: cleanup workflows

* nix: add ci shell

* `octokit` -> `fetch` & cache responses

* nix: use nixpkgs wrangler

* nix: update flake.lock

Flake lock file updates:

• Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/d9c0b9d611277e42e6db055636ba0409c59db6d2' (2024-07-05)
  → 'github:NixOS/nixpkgs/038fb464fcfa79b4f08131b07f2d8c9a6bcc4160' (2024-07-28)

* tsconfig: use strictest

* adopt openapi

* package.json: rename to teawie-api

* nix: add treefmt to ci shell

* ci: add release gate

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -6,49 +6,48 @@ on:
 
 jobs:
   build:
-    runs-on: "ubuntu-latest"
+    name: Build
+
+    runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-      - name: Setup pnpm
-        uses: pnpm/action-setup@v4
+      - name: Install Nix
+        uses: DeterminateSystems/nix-installer-action@v13
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: pnpm
-          cache-dependency-path: pnpm-lock.yaml
-
-      - name: Install dependencies
-        run: pnpm install --frozen-lockfile
+      - name: Install Dependencies
+        run: nix develop .#ci --command pnpm install --frozen-lockfile
 
       - name: Run build
-        run: pnpm build
+        run: nix develop .#ci --command nrr build
 
-  format:
-    runs-on: "ubuntu-latest"
+  treefmt:
+    name: Treefmt
+
+    runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-      - name: Setup pnpm
-        uses: pnpm/action-setup@v4
+      - name: Install Nix
+        uses: DeterminateSystems/nix-installer-action@v13
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: pnpm
-          cache-dependency-path: pnpm-lock.yaml
+      - name: Run checks
+        run: |
+          nix develop .#ci --command treefmt --fail-on-change
 
-      - name: Install dependencies
-        run: pnpm install --frozen-lockfile
+  release-gate:
+    name: CI Release gate
+    needs: [build, treefmt]
 
-      - name: Run Prettier
-        run: pnpm exec prettier --check .
+    if: always()
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Exit with error
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: exit 1
